hpvictus_paths:
  data_root: /home/yeldos/Istanbul/obsidian_vault/work_AITU/IHC/DATASETS/BCData
  checkpoint_dir: /home/yeldos/Istanbul/obsidian_vault/work_AITU/IHC/projects/kiloc/checkpoints

collab_paths:
  data_root: /content/drive/MyDrive/BCData
  checkpoint_dir: /content/BCData_Ki67/checkpoints

h200_paths:
  data_root: /raid/datasets/Yeldos/BCData
  checkpoint_dir: checkpoints